name: analyse

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: ssh2

    - name: Install dependencies
      run: |
        composer install
        composer dump

    - name: Run analyse phpstan
      run: phpstan
