name: Fix Styles

# on:
  # push:
  #   branches: [main]

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install PHP Cs Fixer
        run: |
          composer require --dev friendsofphp/php-cs-fixer

      - name: Fix styles
        run: vendor/bin/php-cs-fixer fix

      - name: Run style
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --format junit
